Repository openshift/pivot, pull requests merged in 2018-09, with the labels that each got.

#10 Misc enhancements
  .gitignore
  .travis.yml
  main.go
  utils/run_test.go
Labels: enhancement

#13 Use pivot:// prefix for rpm-ostree custom URL
  cmd/root.go
Labels: enhancement

#16 cmd: drop networking in the container
  cmd/root.go
Labels: enhancement

#18 Namespace move from ashcrow to openshift
  .travis.yml
  README.md
  cmd/root.go
  main.go
  pivot.spec
Labels: size/S

#19 Miscellaneous patches
  cmd/root.go
Labels: size/S

#20 Pivot to checksum directly, and print OSTree version
  cmd/root.go
Labels: lgtm, size/M
