Repository openshift/pivot, pull requests merged in 2019-03, with the labels that each got.

#40 README.md: Add some more concrete details on how it works
  README.md
Labels: size/XS

#41 Use kubelet auth if available
  cmd/root.go
Labels: size/S

#42 Bump release to 0.0.3-3
  pivot.spec
Labels: size/XS

#45 Bump release to 0.0.3-4
  pivot.spec
Labels: size/XS

#46 Fix previous release bump
  pivot.spec
Labels: size/XS

#47 Add basic kernel tuning functionality
  cmd/root.go
  cmd/root_test.go
  types/tuneargument.go
Labels: lgtm, size/L

#48 Update for 0.0.4 release
  VERSION
  pivot.spec
Labels: size/S
