Repository openshift/pivot, pull requests merged in 2019-05, with the labels that each got.

#52 root: Fix defer call to be after error check
  cmd/root.go
Labels: size/XS

#54 Remove GOCACHE=off for testing and test on 1.12
  .travis.yml
  Makefile
Labels: kind/bug, size/XS

#55 .travis.yml: Remove travis file
  .travis.yml
Labels: lgtm, size/S
