Repository openshift/pivot, pull requests merged in 2019-02, with the labels that each got.

#31 cmd/root: Let rpm-ostree pull from the container repo
  cmd/root.go
Labels: lgtm, size/S

#25 Add pivot.service as a host API
  .gitignore
  Makefile
  README.md
  cmd/root.go
  pivot.spec
  systemd/pivot.service.in
  utils/fs.go
Labels: size/L

#33 VERSION: 0.0.3
  VERSION
Labels: size/XS

#34 tests: Set GOCACHE=off
  Makefile
Labels: size/XS

#37 Various README.md tweaks
  README.md
Labels: kind/documentation, size/S

#38 service: Use Type=oneshot
  systemd/pivot.service.in
Labels: size/XS

#39 Bump release to 0.0.3-2
  pivot.spec
Labels: size/XS
